version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: user_db
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: user_service
    ports:
      - 5433:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
